### ISSUE TITLE
High vulnerability on CGI bundled in td-agent 4.3.1

### ISSUE THREAD

**Issue by chaitrahegde115** [fluent/fluent-package-builder#395]
Hi,
  I am using td-agent 4.3.1. Below vulnerability is reported on cgi (default: 0.1.0.1) 
1. GHSA-5cqm-crxm-6qpv
2. GHSA-4vf4-qmvg-mh7h
What is the impact of these vulnerabilities on td-agent? and what is the fix plan

**Comment by ashie** [comment]
CGI gem is bundled in Ruby, and they are already fixed in Ruby 2.7.5:
https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/

td-agent 4.3.0 bundles Ruby 2.7.5 and  td-agent 4.3.1 bundles Ruby 2.7.6, so it's already fixed.

BTW which tool are you using for scanning vulnerabilities?
I'm bothering with this kind of false positive report.
